### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzureDevOpsStatistics#1]
- [x] Add PRs
- [x] Handle orgs with minimal access
- [x] Count TFVC repos
- [x] Output to CSV
- [x] Harden/ bug fixes
- [x] Update Readme
- [ ] Release
